### ISSUE TITLE
Database Edits

### ISSUE THREAD

**Issue by dv8godd** [dv8godd/GunsKillPeople#7]
Fix MySQL fields that include spaces and update the PHP accordingly. Also consider editing the PHP to not alias any field names, if possible.

**Comment by fhaseltine** [comment]
Should I do this now in the database. and then I can give you the updates.

Do you also want me to change the __pk_  fields
All the spaces were in the Shooting table.  they came from Mother Jones that way.

**Comment by dv8godd** [comment]
I'm converting the PHP to use your __pk_ field names, so leave those.  They're valid names for objects/variables in JavaScript, so it's fine.  I only converted them because I wasn't sure whether the JavaScript would like them, but it turns out it doesn't care.  Next JS and PHP update should look more like your database names.
